-- MySQL Script generated by MySQL Workbench
-- Fri Aug  2 22:30:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taf_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taf_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taf_db` DEFAULT CHARACTER SET utf8 ;
USE `taf_db` ;

-- -----------------------------------------------------
-- Table `taf_db`.`clanky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taf_db`.`clanky` (
  `id_clanek` INT NOT NULL,
  `nazev` VARCHAR(120) NULL,
  `nahledak` VARCHAR(120) NULL,
  PRIMARY KEY (`id_clanek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taf_db`.`clanky_sekce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taf_db`.`clanky_sekce` (
  `id_sekce` INT NOT NULL,
  `id_clanek` INT NOT NULL,
  `nadpis` VARCHAR(120) NULL,
  PRIMARY KEY (`id_sekce`),
  INDEX `fk_clanky_sekce_clanky_idx` (`id_clanek` ASC) VISIBLE,
  CONSTRAINT `fk_clanky_sekce_clanky`
    FOREIGN KEY (`id_clanek`)
    REFERENCES `taf_db`.`clanky` (`id_clanek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taf_db`.`clanky_odstavce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taf_db`.`clanky_odstavce` (
  `id_sekce` INT NOT NULL,
  `text_odstavce` VARCHAR(1024) NOT NULL,
  `odstavec_s_obrazkem` TINYINT NOT NULL,
  `obrazek` VARCHAR(120) NULL,
  INDEX `fk_clanky_odstavce_clanky_sekce1_idx` (`id_sekce` ASC) VISIBLE,
  CONSTRAINT `fk_clanky_odstavce_clanky_sekce1`
    FOREIGN KEY (`id_sekce`)
    REFERENCES `taf_db`.`clanky_sekce` (`id_sekce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
